CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    isadmin BOOLEAN DEFAULT FALSE,
    cpu INT DEFAULT 100,
    ram INT DEFAULT 2048,
    disk INT DEFAULT 10240,
    time VARCHAR(50) DEFAULT '5h',
    used_cpu INT DEFAULT 0,
    used_ram INT DEFAULT 0,
    used_disk INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
